name: Deploy to Staging Server

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      server-path:
        description: "Optional override for the staging server path"
        required: false
        default: ""

env:
  DEFAULT_SERVER_PATH: ~/Desktop/workspace/server/minecraft-staging/data

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resolve target path
        id: resolve
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.server-path }}" ]; then
            echo "value=${{ github.event.inputs.server-path }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=${{ env.DEFAULT_SERVER_PATH }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Run staging deploy script
        run: |
          chmod +x scripts/deploy_staging.sh
          scripts/deploy_staging.sh "${{ steps.resolve.outputs.value }}"
